# Basic site settings
title: MSc MADE data-1            # The title of your website
description: Rosa Storm, Kiki Pool, Orlando Closs, Stijn Mevis # A short description of your site
url: "https://orlandocloss.github.io"   # Replace with your GitHub Pages URL
baseurl: "data1"                         # Leave empty if deploying to https://username.github.io/

# Theme settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme           # add this line to the plugins list if you already have one

# Markdown settings
markdown: kramdown                   # Jekyll uses kramdown by default for Markdown

# Optional: Social media links
github_username: orlandocloss         # Your GitHub username (if you want to display a link)

# Exclude these files from being included in the site
exclude:
  - README.md
  - LICENSE.txt
