# Basic site settings
title: MSc MADE data-1            # The title of your website
description: Rosa Storm, Kiki Pool, Orlando Closs, Stijn Mevis
url: "https://orlandocloss.github.io"   # Replace with your GitHub Pages URL
baseurl: "/data1"                 # Use '/data-1' since you're deploying to a subdirectory

# Theme settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown settings
markdown: kramdown                 # Jekyll uses kramdown by default for Markdown
