# Basic site settings
title: MSc MADE data-1            # The title of your website
description: Rosa Storm, Kiki Pool, Orlando Closs, Stijn Mevis # A short description of your site
url: "https://orlandocloss.github.io"   # Replace with your GitHub Pages URL
baseurl: "data1"                         # Leave empty if deploying to https://username.github.io/
