# Basic site settings
title: MSc MADE data-1            # The title of your website
description: Rosa Storm, Kiki Pool, Orlando Closs, Stijn Mevis
url: "https://orlandocloss.github.io"   # Replace with your GitHub Pages URL
baseurl: "/data1"                 # Use '/data-1' since you're deploying to a subdirectory

# # Theme settings
# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: pages-themes/merlot@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navigation:
  - title: "Home"
    url: "/"
  - title: "Homework-0"
    url: "/homework-0"
  - title: "Assignment-2"
    url: "/assignment2"

# Markdown settings
markdown: kramdown                 # Jekyll uses kramdown by default for Markdown
